In [1]:
import random
import numpy as np
import pandas as pd

with open("names.txt",encoding="utf-8") as file:
    content = file.read()

names_list = content.split()
names = random.choices(names_list,k=50)

with open("names.txt",encoding="utf-8") as file:
    content = file.read()
    
scores = np.random.randint(50,101,size=(50,5))
student_df = pd.DataFrame(scores,
             columns=['國文','英文','數學','地理','歷史'],
             index=names)
student_df

      國文   英文   數學   地理   歷史
黃政甫   96   80   86   97   61
李佳彥   55   73   53   90   59
林怡偉   99   57   96   71   72
鄧淑娟   69   51   78   69   73
吳麗卿   53   76   63   57  100
蘇婷婷   66   51   69   90   56
王良斌   71   95   98   60   65
林冠蕙   54   53   98   53   84
陳信念   84   77   59   78   67
馮芳如   63   87   66   96   75
游淑惠   72   66   96   76   91
黃婷婷   74   54   73   57   76
蔡欣汝   87   86   50   65   99
陳向愛   91   65   65   89   58
王泓泰   59   76   89   67   69
李進慧   60   80   75   58   52
郎慧萍   68   73   74   64   96
蔡偉成   79   71   62  100   70
黃詩妃   80   80   79   85   82
余丞苓   92   92   93   89   80
唐雪豪   62   83   85   80   69
李慈啟   94   92   72   72   83
黃偉剛   50   75   86   92   89
高俊男   67   84   81   80   75
沈心利   63   71   58   61   68
王筱婷   76   62   67   73   65
賴佳雯   57   85   93   61   61
方雅慧   54   59   92   73   52
潘俊賢  100   94   71   55   89
周琬婷   94   82   55   61   83
朱士弘   64   63   83   73   58
陳得映   79   61   72   71   74
周芷蓁   66   62  100   91   77
謝南慧   66   52   59   51   53
陳美惠   71   60   98   98   80
賴又琦   65   99   92   94   58
藍姿婷  100   99   82   96   94
孫火清   66   86   66   82   50
劉旭士   84   89   66   91   56
游倫城   88  100   73   50   71
張家秀   92   93   73   84   66
沈心利   51   88   96   83  100
林世城   97   56   53   50   63
陳彥治   64   57   55   80   63
戴萱能   77   51   91   90   54
尚偉倫   97   75   77   78   97
賴昌韻   52  100   62   60   83
林珍旺   71   54   56   51   54
黃詩妃   95   87   75   91   76
陳凱翔   73   68   77   93   67

In [5]:
student_df[['國文','英文']]

      國文   英文
黃政甫   96   80
李佳彥   55   73
林怡偉   99   57
鄧淑娟   69   51
吳麗卿   53   76
蘇婷婷   66   51
王良斌   71   95
林冠蕙   54   53
陳信念   84   77
馮芳如   63   87
游淑惠   72   66
黃婷婷   74   54
蔡欣汝   87   86
陳向愛   91   65
王泓泰   59   76
李進慧   60   80
郎慧萍   68   73
蔡偉成   79   71
黃詩妃   80   80
余丞苓   92   92
唐雪豪   62   83
李慈啟   94   92
黃偉剛   50   75
高俊男   67   84
沈心利   63   71
王筱婷   76   62
賴佳雯   57   85
方雅慧   54   59
潘俊賢  100   94
周琬婷   94   82
朱士弘   64   63
陳得映   79   61
周芷蓁   66   62
謝南慧   66   52
陳美惠   71   60
賴又琦   65   99
藍姿婷  100   99
孫火清   66   86
劉旭士   84   89
游倫城   88  100
張家秀   92   93
沈心利   51   88
林世城   97   56
陳彥治   64   57
戴萱能   77   51
尚偉倫   97   75
賴昌韻   52  100
林珍旺   71   54
黃詩妃   95   87
陳凱翔   73   68

In [6]:
student_df.loc[['黃詩妃','林珍旺']]

     國文  英文  數學  地理  歷史
黃詩妃  80  80  79  85  82
黃詩妃  95  87  75  91  76
林珍旺  71  54  56  51  54

In [9]:
student_df.iloc[0]
student_df.iloc[0,49]
student_df.iloc[:5]
student_df.iloc[-5:]

     國文   英文  數學  地理  歷史
尚偉倫  97   75  77  78  97
賴昌韻  52  100  62  60  83
林珍旺  71   54  56  51  54
黃詩妃  95   87  75  91  76
陳凱翔  73   68  77  93  67

In [10]:
student_df.iloc[-5:,:3]

     國文   英文  數學
尚偉倫  97   75  77
賴昌韻  52  100  62
林珍旺  71   54  56
黃詩妃  95   87  75
陳凱翔  73   68  77

In [11]:
student_df[student_df['英文'] <60]

     國文  英文  數學  地理  歷史
林怡偉  99  57  96  71  72
鄧淑娟  69  51  78  69  73
蘇婷婷  66  51  69  90  56
林冠蕙  54  53  98  53  84
黃婷婷  74  54  73  57  76
方雅慧  54  59  92  73  52
謝南慧  66  52  59  51  53
林世城  97  56  53  50  63
陳彥治  64  57  55  80  63
戴萱能  77  51  91  90  54
林珍旺  71  54  56  51  54

In [12]:
student_df[(student_df['英文'] <60)&(student_df['地理'] <60)]

     國文  英文  數學  地理  歷史
林冠蕙  54  53  98  53  84
黃婷婷  74  54  73  57  76
謝南慧  66  52  59  51  53
林世城  97  56  53  50  63
林珍旺  71  54  56  51  54

In [13]:
student_df[(student_df['數學'] <60)|(student_df['歷史'] <60)]

     國文  英文  數學  地理  歷史
李佳彥  55  73  53  90  59
蘇婷婷  66  51  69  90  56
陳信念  84  77  59  78  67
蔡欣汝  87  86  50  65  99
陳向愛  91  65  65  89  58
李進慧  60  80  75  58  52
沈心利  63  71  58  61  68
方雅慧  54  59  92  73  52
周琬婷  94  82  55  61  83
朱士弘  64  63  83  73  58
謝南慧  66  52  59  51  53
賴又琦  65  99  92  94  58
孫火清  66  86  66  82  50
劉旭士  84  89  66  91  56
林世城  97  56  53  50  63
陳彥治  64  57  55  80  63
戴萱能  77  51  91  90  54
林珍旺  71  54  56  51  54